name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *" # Her 6 saatte bir çalışır
  workflow_dispatch: # Manuel tetikleme sağlar

jobs:
  build:
    runs-on: ubuntu-latest
    # Hatanın ana çözümü: Yazma izni ekliyoruz
    permissions: 
      contents: write
      
    steps:
      - uses: actions/checkout@v2

      # Yılanı oluşturur
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: BurakcanKiraz
          # Çıktıları 'dist' klasörüne kaydeder
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      # Oluşan dosyaları 'output' branch'ine yükler
      - uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
